.PHONY: run migrate createsuperuser test

run:
	poetry run python manage.py runserver

migrate:
	poetry run python manage.py migrate

createsuperuser:
	poetry run python manage.py createsuperuser

test:
	poetry run pytest

